// Login
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

// Podcast
export const GET_EPISODES_SUCCESS = 'GET_EPISODES_SUCCESS';
export const GET_EPISODES_FAIL = 'GET_EPISODES_FAIL';
export const ADD_EPISODE_SUCCESS = 'ADD_EPISODE_SUCCESS';
export const ADD_EPISODE_FAIL = 'ADD_EPISODE_FAIL';

// Workshops
export const GET_WORKSHOPS_SUCCESS = 'GET_WORKSHOPS_SUCCESS';
export const GET_WORKSHOPS_FAIL = 'GET_WORKSHOPS_FAIL';

// Mailing List
export const GET_MAILING_LIST_SUCCESS = 'GET_MAILING_LIST_SUCCESS';
export const GET_MAILING_LIST_FAIL = 'GET_MAILING_LIST_FAIL';
